[2020-04-27 00:12:42,286] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.persiste_dados_mongodb 2020-04-26T23:42:03.854394+00:00 [queued]>
[2020-04-27 00:12:42,322] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.persiste_dados_mongodb 2020-04-26T23:42:03.854394+00:00 [queued]>
[2020-04-27 00:12:42,322] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-27 00:12:42,322] {{taskinstance.py:867}} INFO - Starting attempt 2 of 2
[2020-04-27 00:12:42,323] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-27 00:12:42,340] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): persiste_dados_mongodb> on 2020-04-26T23:42:03.854394+00:00
[2020-04-27 00:12:42,344] {{standard_task_runner.py:53}} INFO - Started process 18005 to run task
[2020-04-27 00:12:42,417] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui-scraping_scores.persiste_dados_mongodb 2020-04-26T23:42:03.854394+00:00 [running]> 030a07de9129.semantix
[2020-04-27 00:12:42,450] {{taskinstance.py:1128}} ERROR - dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 109, in execute
    context.update(self.op_kwargs)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
[2020-04-27 00:12:42,451] {{taskinstance.py:1170}} INFO - All retries failed; marking task as FAILED.dag_id=ReclameAqui-scraping_scores, task_id=persiste_dados_mongodb, execution_date=20200426T234203, start_date=20200427T001242, end_date=20200427T001242
[2020-04-27 00:12:52,253] {{logging_mixin.py:112}} INFO - [2020-04-27 00:12:52,252] {{local_task_job.py:103}} INFO - Task exited with return code 1
