[2020-04-26 18:59:35,456] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T18:59:29.191283+00:00 [queued]>
[2020-04-26 18:59:35,504] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T18:59:29.191283+00:00 [queued]>
[2020-04-26 18:59:35,504] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 18:59:35,504] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 18:59:35,504] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 18:59:35,543] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): persiste_dados_mongodb> on 2020-04-26T18:59:29.191283+00:00
[2020-04-26 18:59:35,549] {{standard_task_runner.py:53}} INFO - Started process 18462 to run task
[2020-04-26 18:59:35,683] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T18:59:29.191283+00:00 [running]> 030a07de9129.semantix
[2020-04-26 18:59:35,727] {{taskinstance.py:1128}} ERROR - crud_main() missing 5 required positional arguments: 'metod', 'company', 'collection', 'date', and 'jsondata'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: crud_main() missing 5 required positional arguments: 'metod', 'company', 'collection', 'date', and 'jsondata'
[2020-04-26 18:59:35,729] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-26 18:59:45,413] {{logging_mixin.py:112}} INFO - [2020-04-26 18:59:45,412] {{local_task_job.py:103}} INFO - Task exited with return code 1
