[2020-04-26 17:42:50,213] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:42:44.363392+00:00 [queued]>
[2020-04-26 17:42:50,270] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:42:44.363392+00:00 [queued]>
[2020-04-26 17:42:50,272] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:42:50,273] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 17:42:50,275] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:42:50,322] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): persiste_dados_mongodb> on 2020-04-26T17:42:44.363392+00:00
[2020-04-26 17:42:50,331] {{standard_task_runner.py:53}} INFO - Started process 6470 to run task
[2020-04-26 17:42:50,543] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:42:44.363392+00:00 [running]> 61b2702b37e2.semantix
[2020-04-26 17:42:50,616] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2020-04-26 17:42:50,620] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpd5ybkaot/persiste_dados_mongodbgrsw02tb
[2020-04-26 17:42:50,621] {{bash_operator.py:115}} INFO - Running command: /usr/local/airflow/dags/scripts/requests_database.py --metod 'POST' --company 'Cielo' --collection 'scores' --jsondata {"answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}
[2020-04-26 17:42:50,638] {{bash_operator.py:122}} INFO - Output:
[2020-04-26 17:42:51,223] {{bash_operator.py:126}} INFO - usage: requests_database.py [-h] --metod METOD --company COMPANY --collection
[2020-04-26 17:42:51,223] {{bash_operator.py:126}} INFO -                             COLLECTION [--date DATE]
[2020-04-26 17:42:51,223] {{bash_operator.py:126}} INFO - requests_database.py: error: unrecognized arguments: --jsondata {answered: 6666, reclamations: 6151, response_time: 15 dias e 21 horas , unanswered: 113}
[2020-04-26 17:42:51,224] {{bash_operator.py:126}} INFO - Inicio processo
[2020-04-26 17:42:51,259] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2020-04-26 17:42:51,273] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-04-26 17:42:51,277] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-26 17:43:00,146] {{logging_mixin.py:112}} INFO - [2020-04-26 17:43:00,145] {{local_task_job.py:103}} INFO - Task exited with return code 1
