[2020-04-26 17:27:27,632] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:27:21.523934+00:00 [queued]>
[2020-04-26 17:27:27,679] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:27:21.523934+00:00 [queued]>
[2020-04-26 17:27:27,681] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:27:27,682] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 17:27:27,683] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:27:27,740] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): persiste_dados_mongodb> on 2020-04-26T17:27:21.523934+00:00
[2020-04-26 17:27:27,753] {{standard_task_runner.py:53}} INFO - Started process 29344 to run task
[2020-04-26 17:27:27,932] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:27:21.523934+00:00 [running]> 61b2702b37e2.semantix
[2020-04-26 17:27:27,996] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2020-04-26 17:27:27,998] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpp_1npo__/persiste_dados_mongodbhhn3brv4
[2020-04-26 17:27:27,999] {{bash_operator.py:115}} INFO - Running command: /usr/local/airflow/dags/scripts/requests_database.py --metod 'POST' --company 'Cielo' --collection 'scores' --jsondata '{'answered': '6666', 'reclamations': '6151', 'response_time': '15 dias e 21 horas ', 'unanswered': '113'}'
[2020-04-26 17:27:28,016] {{bash_operator.py:122}} INFO - Output:
[2020-04-26 17:27:28,573] {{bash_operator.py:126}} INFO - usage: requests_database.py [-h] --metod METOD --company COMPANY --collection
[2020-04-26 17:27:28,574] {{bash_operator.py:126}} INFO -                             COLLECTION [--date DATE] [--jsondata JSONDATA]
[2020-04-26 17:27:28,574] {{bash_operator.py:126}} INFO - requests_database.py: error: unrecognized arguments: dias e 21 horas , unanswered: 113}
[2020-04-26 17:27:28,574] {{bash_operator.py:126}} INFO - Inicio processo
[2020-04-26 17:27:28,645] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2020-04-26 17:27:28,669] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-04-26 17:27:28,672] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-26 17:27:37,546] {{logging_mixin.py:112}} INFO - [2020-04-26 17:27:37,545] {{local_task_job.py:103}} INFO - Task exited with return code 1
