[2020-04-27 00:12:42,277] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-26T00:00:00+00:00 [queued]>
[2020-04-27 00:12:42,309] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-26T00:00:00+00:00 [queued]>
[2020-04-27 00:12:42,310] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-27 00:12:42,310] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-27 00:12:42,310] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-27 00:12:42,329] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): scores_reclameaqui> on 2020-04-26T00:00:00+00:00
[2020-04-27 00:12:42,334] {{standard_task_runner.py:53}} INFO - Started process 18004 to run task
[2020-04-27 00:12:42,408] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-26T00:00:00+00:00 [running]> 030a07de9129.semantix
[2020-04-27 00:12:42,435] {{taskinstance.py:1128}} ERROR - get_reclameaqui() got an unexpected keyword argument 'conf'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_reclameaqui() got an unexpected keyword argument 'conf'
[2020-04-27 00:12:42,437] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-27 00:12:52,253] {{logging_mixin.py:112}} INFO - [2020-04-27 00:12:52,252] {{local_task_job.py:103}} INFO - Task exited with return code 1
