[2020-04-26 17:15:15,739] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:15:09.990813+00:00 [queued]>
[2020-04-26 17:15:15,779] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:15:09.990813+00:00 [queued]>
[2020-04-26 17:15:15,779] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:15:15,780] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 17:15:15,780] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:15:15,816] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): persiste_dados_mongodb> on 2020-04-26T17:15:09.990813+00:00
[2020-04-26 17:15:15,825] {{standard_task_runner.py:53}} INFO - Started process 21584 to run task
[2020-04-26 17:15:15,919] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:15:09.990813+00:00 [running]> 61b2702b37e2.semantix
[2020-04-26 17:15:15,950] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2020-04-26 17:15:15,951] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpakh13mfe/persiste_dados_mongodbwgsomt_1
[2020-04-26 17:15:15,951] {{bash_operator.py:115}} INFO - Running command: ./scripts/requests_database.py --metod POST --company Cielo --collection scores --jsondata {'answered': '6666', 'reclamations': '6151', 'response_time': '15 dias e 21 horas ', 'unanswered': '113'}
[2020-04-26 17:15:15,960] {{bash_operator.py:122}} INFO - Output:
[2020-04-26 17:15:15,962] {{bash_operator.py:126}} INFO - /tmp/airflowtmpakh13mfe/persiste_dados_mongodbwgsomt_1: line 1: ./scripts/requests_database.py: No such file or directory
[2020-04-26 17:15:15,963] {{bash_operator.py:130}} INFO - Command exited with return code 127
[2020-04-26 17:15:15,976] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-04-26 17:15:15,978] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-26 17:15:25,665] {{logging_mixin.py:112}} INFO - [2020-04-26 17:15:25,665] {{local_task_job.py:103}} INFO - Task exited with return code 1
