[2020-04-27 00:18:04,766] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.persiste_dados_mongodb 2020-04-27T00:17:28.643430+00:00 [queued]>
[2020-04-27 00:18:04,801] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.persiste_dados_mongodb 2020-04-27T00:17:28.643430+00:00 [queued]>
[2020-04-27 00:18:04,802] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-27 00:18:04,802] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-27 00:18:04,803] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-27 00:18:04,820] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): persiste_dados_mongodb> on 2020-04-27T00:17:28.643430+00:00
[2020-04-27 00:18:04,825] {{standard_task_runner.py:53}} INFO - Started process 21373 to run task
[2020-04-27 00:18:04,899] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui-scraping_scores.persiste_dados_mongodb 2020-04-27T00:17:28.643430+00:00 [running]> 030a07de9129.semantix
[2020-04-27 00:18:04,946] {{taskinstance.py:1128}} ERROR - dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 109, in execute
    context.update(self.op_kwargs)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
[2020-04-27 00:18:04,948] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-27 00:18:14,746] {{logging_mixin.py:112}} INFO - [2020-04-27 00:18:14,745] {{local_task_job.py:103}} INFO - Task exited with return code 1
