[2020-04-26 17:09:15,335] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-24T00:00:00+00:00 [queued]>
[2020-04-26 17:09:15,360] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-24T00:00:00+00:00 [queued]>
[2020-04-26 17:09:15,364] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:09:15,365] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 17:09:15,365] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:09:15,390] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): persiste_dados_mongodb> on 2020-04-24T00:00:00+00:00
[2020-04-26 17:09:15,395] {{standard_task_runner.py:53}} INFO - Started process 17808 to run task
[2020-04-26 17:09:15,513] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-24T00:00:00+00:00 [running]> 61b2702b37e2.semantix
[2020-04-26 17:09:15,564] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2020-04-26 17:09:15,567] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmp1ejwj6_m/persiste_dados_mongodb8yl8xhtq
[2020-04-26 17:09:15,567] {{bash_operator.py:115}} INFO - Running command: ./requests_database.py --metod POST --company Cielo --collection scores --jsondata {'answered': '6666', 'reclamations': '6151', 'response_time': '15 dias e 21 horas ', 'unanswered': '113'}
[2020-04-26 17:09:15,581] {{bash_operator.py:122}} INFO - Output:
[2020-04-26 17:09:15,597] {{bash_operator.py:126}} INFO - /tmp/airflowtmp1ejwj6_m/persiste_dados_mongodb8yl8xhtq: line 1: ./requests_database.py: No such file or directory
[2020-04-26 17:09:15,598] {{bash_operator.py:130}} INFO - Command exited with return code 127
[2020-04-26 17:09:15,615] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-04-26 17:09:15,618] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-26 17:09:25,309] {{logging_mixin.py:112}} INFO - [2020-04-26 17:09:25,308] {{local_task_job.py:103}} INFO - Task exited with return code 1
