[2020-04-26 17:30:22,952] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:25:12.611350+00:00 [queued]>
[2020-04-26 17:30:22,970] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:25:12.611350+00:00 [queued]>
[2020-04-26 17:30:22,970] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:30:22,970] {{taskinstance.py:867}} INFO - Starting attempt 2 of 2
[2020-04-26 17:30:22,970] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:30:22,985] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): persiste_dados_mongodb> on 2020-04-26T17:25:12.611350+00:00
[2020-04-26 17:30:22,989] {{standard_task_runner.py:53}} INFO - Started process 31211 to run task
[2020-04-26 17:30:23,047] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:25:12.611350+00:00 [running]> 61b2702b37e2.semantix
[2020-04-26 17:30:23,067] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2020-04-26 17:30:23,068] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpqz2gmez9/persiste_dados_mongodbtyy8bgvi
[2020-04-26 17:30:23,068] {{bash_operator.py:115}} INFO - Running command: /usr/local/airflow/dags/scripts/requests_database.py --metod 'POST' --company 'Cielo' --collection 'scores' --jsondata {"answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}
[2020-04-26 17:30:23,075] {{bash_operator.py:122}} INFO - Output:
[2020-04-26 17:30:23,286] {{bash_operator.py:126}} INFO - usage: requests_database.py [-h] --metod METOD --company COMPANY --collection
[2020-04-26 17:30:23,287] {{bash_operator.py:126}} INFO -                             COLLECTION [--date DATE] [--jsondata JSONDATA]
[2020-04-26 17:30:23,287] {{bash_operator.py:126}} INFO - requests_database.py: error: unrecognized arguments: 6666, reclamations: 6151, response_time: 15 dias e 21 horas , unanswered: 113}
[2020-04-26 17:30:23,287] {{bash_operator.py:126}} INFO - Inicio processo
[2020-04-26 17:30:23,307] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2020-04-26 17:30:23,317] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-04-26 17:30:23,318] {{taskinstance.py:1170}} INFO - All retries failed; marking task as FAILED.dag_id=ReclameAqui, task_id=persiste_dados_mongodb, execution_date=20200426T172512, start_date=20200426T173022, end_date=20200426T173023
[2020-04-26 17:30:32,950] {{logging_mixin.py:112}} INFO - [2020-04-26 17:30:32,950] {{local_task_job.py:103}} INFO - Task exited with return code 1
